<H1><CENTER><u>HEALTHCARE RISK FACTORS ANALYSIS</u></CENTER></H1>

<h2>Data Preprocessing</h2>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## uncleaned dataset

In [2]:
df=pd.read_csv("Healthcare Risk Factors Dataset/dirty_v3_path.csv")
df.head()

,Age,Gender,Medical Condition,Glucose,Blood Pressure,BMI,Oxygen Saturation,LengthOfStay,Cholesterol,Triglycerides,HbA1c,Smoking,Alcohol,Physical Activity,Diet Score,Family History,Stress Level,Sleep Hours,random_notes,noise_col
0,46.0,Male,Diabetes,137.04,135.27,28.90,96.04,6,231.88,210.56,7.61,0,0,-0.20,3.54,0,5.07,6.05,lorem,-137.057211
1,22.0,Male,Healthy,71.58,113.27,26.29,97.54,2,165.57,129.41,4.91,0,0,8.12,5.90,0,5.87,7.72,ipsum,-11.230610
2,50.0,NaN,Asthma,95.24,NaN,22.53,90.31,2,214.94,165.35,5.60,0,0,5.01,4.65,1,3.09,4.82,ipsum,98.331195
3,57.0,NaN,Obesity,NaN,130.53,38.47,96.60,5,197.71,182.13,6.92,0,0,3.16,3.37,0,3.01,5.33,lorem,44.187175
4,66.0,Female,Hypertension,95.15,178.17,31.12,94.90,4,259.53,115.85,5.98,0,1,3.56,3.40,0,6.38,6.64,lorem,44.831426

In [3]:
df.shape

(30000, 20)

In [4]:
df.columns

Index(['Age', 'Gender', 'Medical Condition', 'Glucose', 'Blood Pressure',
       'BMI', 'Oxygen Saturation', 'LengthOfStay', 'Cholesterol',
       'Triglycerides', 'HbA1c', 'Smoking', 'Alcohol', 'Physical Activity',
       'Diet Score', 'Family History', 'Stress Level', 'Sleep Hours',
       'random_notes', 'noise_col'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                25500 non-null  float64
 1   Gender             25500 non-null  object
 2   Medical Condition  25500 non-null  object
 3   Glucose            25500 non-null  float64
 4   Blood Pressure     25500 non-null  float64
 5   BMI                30000 non-null  float64
 6   Oxygen Saturation  30000 non-null  float64
 7   LengthOfStay       30000 non-null  int64
 8   Cholesterol        30000 non-null  float64
 9   Triglycerides      30000 non-null  float64
 10  HbA1c              30000 non-null  float64
 11  Smoking            30000 non-null  int64
 12  Alcohol            30000 non-null  int64
 13  Physical Activity  30000 non-null  float64
 14  Diet Score         30000 non-null  float64
 15  Family History     30000 non-null  int64
 16  Stress Level       30000 non-null  float64
 17  Sleep Hours        30000 non-null  float64
 18  random_notes       30000 non-null  object
 19  noise_col          30000 non-null  float64
dtypes: float64(13), int64(4), object(3)
memory usage: 4.6+ MB

In [6]:
# descriptive stats
df.describe()

,Age,Glucose,Blood Pressure,BMI,Oxygen Saturation,LengthOfStay,Cholesterol,Triglycerides,HbA1c,Smoking,Alcohol,Physical Activity,Diet Score,Family History,Stress Level,Sleep Hours,noise_col
count,25500.000000,25500.000000,25500.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,54.616784,123.622179,140.455337,28.476155,94.954992,4.414133,213.033891,176.837375,6.294377,0.279767,0.238533,3.803214,4.029654,0.439433,5.917312,6.229836,-0.517010
std,15.973618,41.576943,21.077933,5.728804,3.736202,2.761536,33.519757,48.812827,1.320269,0.448892,0.426194,2.011729,1.817165,0.496326,2.225057,1.187669,100.076959
min,10.000000,20.320000,74.240000,7.670000,67.510000,1.000000,95.730000,-22.480000,3.280000,0.000000,0.000000,-3.680000,-1.750000,0.000000,-2.440000,1.590000,-412.169596
25%,45.000000,96.280000,125.140000,24.590000,93.000000,3.000000,189.500000,141.280000,5.330000,0.000000,0.000000,2.350000,2.770000,0.000000,4.370000,5.410000,-68.270749
50%,55.000000,110.500000,138.320000,28.050000,95.300000,4.000000,211.835000,173.365000,5.970000,0.000000,0.000000,3.590000,3.790000,0.000000,5.900000,6.230000,-0.510742
75%,66.000000,136.610000,153.790000,31.810000,97.380000,5.000000,235.310000,208.630000,6.920000,1.000000,0.000000,5.060000,5.020000,1.000000,7.440000,7.050000,66.811399
max,89.000000,318.510000,226.380000,56.850000,110.070000,19.000000,358.370000,421.510000,12.360000,1.000000,1.000000,12.410000,12.060000,1.000000,15.450000,10.350000,467.894910

In [7]:
num_cols=df.select_dtypes(exclude='O').columns
num_cols

Index(['Age', 'Glucose', 'Blood Pressure', 'BMI', 'Oxygen Saturation',
       'LengthOfStay', 'Cholesterol', 'Triglycerides', 'HbA1c', 'Smoking',
       'Alcohol', 'Physical Activity', 'Diet Score', 'Family History',
       'Stress Level', 'Sleep Hours', 'noise_col'],
      dtype='object')

In [8]:
cat_cols=df.select_dtypes(include='O').columns
cat_cols

Index(['Gender', 'Medical Condition', 'random_notes'], dtype='object')

<h2>Handling Missing Values</h2>

In [9]:
df.isnull().sum()

Age                  4500
Gender               4500
Medical Condition    4500
Glucose              4500
Blood Pressure       4500
BMI                     0
Oxygen Saturation       0
LengthOfStay            0
Cholesterol             0
Triglycerides           0
HbA1c                   0
Smoking                 0
Alcohol                 0
Physical Activity       0
Diet Score              0
Family History          0
Stress Level            0
Sleep Hours             0
random_notes            0
noise_col               0
dtype: int64

In [10]:
# percentage of null values
(df.isnull().sum())/len(df)*100

Age                  15.0
Gender               15.0
Medical Condition    15.0
Glucose              15.0
Blood Pressure       15.0
BMI                   0.0
Oxygen Saturation     0.0
LengthOfStay          0.0
Cholesterol           0.0
Triglycerides         0.0
HbA1c                 0.0
Smoking               0.0
Alcohol               0.0
Physical Activity     0.0
Diet Score            0.0
Family History        0.0
Stress Level          0.0
Sleep Hours           0.0
random_notes          0.0
noise_col             0.0
dtype: float64

<h3>Handling null values of Age column</h3>

In [11]:
df['Age'].describe()

count    25500.000000
mean        54.616784
std         15.973618
min         10.000000
25%         45.000000
50%         55.000000
75%         66.000000
max         89.000000
Name: Age, dtype: float64

In [12]:
df['Age']=df['Age'].fillna(df['Age'].median())

The Age column contained approximately 15% missing values. To handle these missing values, median imputation was used. The median value was chosen instead of the mean because it is less affected by extreme or unusual values that may exist in healthcare data. Descriptive statistics showed that the age distribution was fairly balanced, but using the median provides a more robust and reliable representation of the central age group. This helps maintain the natural distribution of patient ages and reduces the impact of potential outliers.

<h3>Handling null values of gender column</h3>

In [13]:
df['Gender'].value_counts()

Gender
Female    12865
Male      12635
Name: count, dtype: int64

In [14]:
df['Gender']=df['Gender'].fillna('not_specified')

The Gender column contained missing values. Since gender distribution was nearly balanced, mode imputation could introduce slight bias. Therefore, missing values were replaced with "Unknown" to maintain data transparency and avoid assumptions about patient gender.

<h3>Handling null values of Medical condition column</h3>

In [15]:
df['Medical Condition'].value_counts()

Medical Condition
Hypertension    7120
Diabetes        6417
Obesity         3857
Healthy         3039
Asthma          2037
Arthritis       1796
Cancer          1234
Name: count, dtype: int64

In [16]:
df['Medical Condition']=df['Medical Condition'].fillna('Unknown')

In [17]:
df[df['Medical Condition']=='Unknown']

,Age,Gender,Medical Condition,Glucose,Blood Pressure,BMI,Oxygen Saturation,LengthOfStay,Cholesterol,Triglycerides,HbA1c,Smoking,Alcohol,Physical Activity,Diet Score,Family History,Stress Level,Sleep Hours,random_notes,noise_col
20,63.0,Male,Unknown,116.84,147.37,44.69,97.02,5,216.48,150.00,6.29,1,0,0.89,2.17,0,4.17,4.96,###,1.572260
30,62.0,not_specified,Unknown,108.28,NaN,40.01,92.89,4,225.84,153.21,7.68,0,0,4.70,2.75,1,2.75,6.66,??,3.878347
37,63.0,Female,Unknown,NaN,160.71,31.27,93.00,3,181.27,140.16,6.53,1,1,2.71,3.42,0,8.06,3.39,###,-26.261020
47,42.0,Female,Unknown,146.24,122.34,22.80,98.28,6,248.64,199.54,6.82,0,0,4.21,1.81,0,4.50,7.72,ipsum,-63.424308
63,62.0,Male,Unknown,141.31,119.94,22.49,92.93,8,181.95,177.79,8.08,0,0,2.35,2.88,0,7.77,7.71,lorem,9.224788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29980,46.0,Male,Unknown,112.29,139.73,25.09,93.99,3,253.66,231.65,6.83,0,0,4.88,3.62,0,7.99,7.09,###,-148.639343
29983,55.0,Female,Unknown,108.81,NaN,27.84,93.28,3,141.65,140.52,5.86,0,0,5.83,3.51,1,8.95,5.94,??,-92.612279
29989,51.0,Male,Unknown,116.04,158.76,29.84,92.57,2,267.01,227.47,5.05,0,1,1.22,6.00,1,10.00,5.92,??,-13.774762
29993,48.0,Female,Unknown,107.09,163.32,34.40,94.47,2,236.15,181.37,5.43,0,0,4.43,4.93,1,7.55,3.72,lorem,-35.728961
29997,83.0,Female,Unknown,NaN,170.11,30.55,97.83,3,210.13,168.76,5.05,0,0,4.53,4.50,0,4.31,3.61,###,-30.934595

Missing values in the Medical Condition column were replaced with "Not Specified" instead of using the mode. Since medical conditions are sensitive health attributes, replacing missing values with the most frequent condition could introduce bias and misrepresent patient health status. Using "Not Specified" preserves data integrity and allows better interpretation during exploratory analysis.

<h3>Handling null values of Glucose & Blood Pressure  column</h3>

In [18]:
null_cols=['Glucose','Blood Pressure']

In [19]:
for col in null_cols:
    df[col]=df[col].fillna(df[col].median())

Missing values in Glucose and Blood Pressure columns were filled using median values. Median was chosen because these medical measurements may contain extreme values, and median is less affected by outliers. This helped maintain realistic patient health data and ensured the dataset was ready for further analysis.

In [20]:
df.isnull().sum()

Age                  0
Gender               0
Medical Condition    0
Glucose              0
Blood Pressure       0
BMI                  0
Oxygen Saturation    0
LengthOfStay         0
Cholesterol          0
Triglycerides        0
HbA1c                0
Smoking              0
Alcohol              0
Physical Activity    0
Diet Score           0
Family History       0
Stress Level         0
Sleep Hours          0
random_notes         0
noise_col            0
dtype: int64

#### looking like all the values were filled

<h2>Checking Duplicate Rows </h2>

In [21]:
df.duplicated().sum()

np.int64(0)

so in this dataset their is no duplicate records found

<h2>Detecting Outliers </h2>

In [22]:
def detect_outlier(DataFrame:df,col):
    for i in col:
        Q1=df[i].quantile(0.25)
        Q3=df[i].quantile(0.75)
        IQR=Q3-Q1
        lw=Q1-1.5*IQR
        uw=Q3+1.5*IQR
        outliers=df[(df[i]<lw)|(df[i]>uw)]
     
        print(f"{i}")
        print(f"{i}->lw-{lw}")
        print(f"{i}->uw-{uw}")
        print(f"total outlier in {i}-> {len(outliers)}")
        print("--------------------------"*5)

In [23]:
detect_outlier(df,num_cols)

Age
Age->lw-21.5
Age->uw-89.5
total outlier in Age-> 748
----------------------------------------------------------------------------------------------------------------------------------
Glucose
Glucose->lw-53.84499999999999
Glucose->uw-173.88500000000002
total outlier in Glucose-> 3667
----------------------------------------------------------------------------------------------------------------------------------
Blood Pressure
Blood Pressure->lw-93.38000000000002
Blood Pressure->uw-184.98
total outlier in Blood Pressure-> 820
----------------------------------------------------------------------------------------------------------------------------------
BMI
BMI->lw-13.760000000000002
BMI->uw-42.64
total outlier in BMI-> 552
----------------------------------------------------------------------------------------------------------------------------------
Oxygen Saturation
Oxygen Saturation->lw-86.43
Oxygen Saturation->uw-103.94999999999999
total outlier in Oxygen Saturation-> 898
----------------------------------------------------------------------------------------------------------------------------------
LengthOfStay
LengthOfStay->lw-0.0
LengthOfStay->uw-8.0
total outlier in LengthOfStay-> 1246
----------------------------------------------------------------------------------------------------------------------------------
Cholesterol
Cholesterol->lw-120.785
Cholesterol->uw-304.025
total outlier in Cholesterol-> 186
----------------------------------------------------------------------------------------------------------------------------------
Triglycerides
Triglycerides->lw-40.25500000000001
Triglycerides->uw-309.655
total outlier in Triglycerides-> 286
----------------------------------------------------------------------------------------------------------------------------------
HbA1c
HbA1c->lw-2.9450000000000003
HbA1c->uw-9.305
total outlier in HbA1c-> 1051
----------------------------------------------------------------------------------------------------------------------------------
Smoking
Smoking->lw--1.5
Smoking->uw-2.5
total outlier in Smoking-> 0
----------------------------------------------------------------------------------------------------------------------------------
Alcohol
Alcohol->lw-0.0
Alcohol->uw-0.0
total outlier in Alcohol-> 7156
----------------------------------------------------------------------------------------------------------------------------------
Physical Activity
Physical Activity->lw--1.7149999999999994
Physical Activity->uw-9.125
total outlier in Physical Activity-> 282
----------------------------------------------------------------------------------------------------------------------------------
Diet Score
Diet Score->lw--0.6049999999999991
Diet Score->uw-8.395
total outlier in Diet Score-> 692
----------------------------------------------------------------------------------------------------------------------------------
Family History
Family History->lw--1.5
Family History->uw-2.5
total outlier in Family History-> 0
----------------------------------------------------------------------------------------------------------------------------------
Stress Level
Stress Level->lw--0.23500000000000032
Stress Level->uw-12.045000000000002
total outlier in Stress Level-> 139
----------------------------------------------------------------------------------------------------------------------------------
Sleep Hours
Sleep Hours->lw-2.9500000000000006
Sleep Hours->uw-9.51
total outlier in Sleep Hours-> 132
----------------------------------------------------------------------------------------------------------------------------------
noise_col
noise_col->lw--270.8939719000074
noise_col->uw-269.43462193883704
total outlier in noise_col-> 217
----------------------------------------------------------------------------------------------------------------------------------

In [24]:
Q1=df['Glucose'].quantile(0.25)
Q3=df['Glucose'].quantile(0.75)
IQR=Q3-Q1
lw=Q1-1.5*IQR
uw=Q3+1.5*IQR
out=df[(df['Glucose']<lw)|(df['Glucose']>uw)]
out.head(25)

,Age,Gender,Medical Condition,Glucose,Blood Pressure,BMI,Oxygen Saturation,LengthOfStay,Cholesterol,Triglycerides,HbA1c,Smoking,Alcohol,Physical Activity,Diet Score,Family History,Stress Level,Sleep Hours,random_notes,noise_col
16,45.0,Male,Diabetes,204.82,135.38,29.67,88.88,5,194.29,94.98,8.70,1,1,3.98,2.58,1,5.91,6.03,###,-32.371503
17,64.0,Female,Diabetes,278.41,151.13,33.49,95.79,6,222.42,148.66,7.68,0,1,1.10,3.40,0,7.52,5.94,??,130.220928
18,55.0,Female,Diabetes,219.73,157.39,29.21,95.93,5,213.50,219.72,7.06,0,0,4.38,2.21,1,7.92,6.06,ipsum,105.291688
23,63.0,Male,Diabetes,198.52,142.32,33.84,90.77,3,177.28,64.13,7.92,0,0,2.25,2.56,0,4.89,6.17,###,-32.924575
24,58.0,Male,Diabetes,184.13,143.06,33.54,88.40,4,223.54,141.01,7.37,1,0,3.69,2.73,1,8.02,7.11,lorem,220.066222
27,45.0,not_specified,Diabetes,223.90,127.73,31.45,95.75,7,150.75,195.63,9.65,1,0,4.10,1.42,0,5.47,6.02,ipsum,50.805390
36,53.0,Female,Diabetes,190.55,149.88,24.11,94.85,7,160.97,189.33,8.58,0,0,4.83,2.30,1,3.72,5.89,??,35.776140
60,55.0,Female,Diabetes,250.68,170.15,27.67,95.24,3,201.66,159.28,9.21,0,0,2.31,3.53,1,6.67,6.95,###,3.189116
64,46.0,Female,Diabetes,197.78,138.32,30.80,94.84,4,160.98,174.05,8.75,1,0,3.70,2.27,0,9.87,7.28,ipsum,17.620628
82,63.0,Female,Diabetes,216.14,140.26,39.76,94.37,5,171.28,179.08,7.85,0,1,1.49,3.86,1,4.38,6.72,??,-115.756249
95,50.0,Male,Diabetes,193.76,144.01,32.10,100.51,5,168.59,189.24,9.11,0,1,4.04,4.01,0,4.48,6.96,ipsum,209.891154
96,69.0,not_specified,Diabetes,243.31,137.10,32.18,99.14,7,221.25,195.91,8.56,0,0,1.81,2.11,0,4.38,4.84,lorem,109.151485
102,55.0,Male,Diabetes,215.76,155.44,35.14,104.06,4,197.97,148.25,5.52,1,0,2.29,4.12,0,7.75,5.44,ipsum,58.173275
103,73.0,Male,Unknown,187.88,159.16,26.49,98.47,4,253.58,190.60,11.10,0,1,0.71,4.33,1,2.37,3.92,###,22.278925
106,55.0,Male,Diabetes,222.06,138.32,29.99,94.23,3,178.24,159.23,9.02,0,0,1.54,1.60,1,6.09,5.19,ipsum,32.500646
110,42.0,Female,Diabetes,208.87,138.32,32.14,96.93,4,256.75,166.18,9.78,0,0,2.90,3.26,1,6.29,5.83,lorem,-88.419465
129,61.0,Female,Diabetes,218.56,138.32,25.03,94.92,3,161.51,158.37,6.08,0,0,3.86,1.57,1,4.50,6.28,lorem,13.447856
130,46.0,Female,Diabetes,220.95,139.97,26.71,91.50,8,230.92,156.72,8.37,0,0,2.47,1.75,1,9.64,7.03,lorem,-29.868317
133,57.0,not_specified,Diabetes,246.27,126.45,35.78,93.02,6,203.78,231.08,7.59,0,1,2.19,2.09,1,8.83,6.39,??,-60.246572
135,66.0,Male,Diabetes,174.96,138.32,40.53,92.36,5,202.94,163.32,7.17,0,0,0.55,3.29,1,10.57,6.17,ipsum,74.119607
144,54.0,not_specified,Diabetes,201.27,130.13,26.11,93.02,5,227.20,121.87,6.03,0,0,4.06,2.28,1,7.12,6.72,??,-104.486186
147,49.0,Male,Diabetes,195.54,153.01,30.65,90.30,3,220.06,133.36,9.01,1,0,2.86,3.16,0,5.32,4.59,ipsum,4.297500
153,51.0,Female,Diabetes,196.41,138.32,26.53,89.65,5,182.17,164.79,6.99,0,0,3.22,3.34,0,6.71,6.52,??,-40.132890
177,44.0,not_specified,Diabetes,183.47,138.67,28.63,90.55,3,162.70,205.41,8.76,1,0,2.15,3.56,0,9.68,5.21,lorem,-17.538592
180,44.0,Female,Diabetes,180.68,127.93,32.34,88.06,5,167.78,157.84,7.84,0,1,1.35,1.95,1,7.56,5.36,###,37.686663

<h2>Droping Irrelevant Columns</h2>

In [25]:
df['random_notes'].unique()

array(['lorem', 'ipsum', '###', '??'], dtype=object)

The column random_notes was removed because it contains random textual information without any medical meaning. The values are placeholders or irrelevant strings that do not contribute to any analysis or insights. Retaining this column would only add bais to the dataset, so it was dropped.

In [26]:
# nunique finds total no of unique values
df['noise_col'].nunique()

30000

In [27]:
if 'noise_col' in df.select_dtypes(include='number').columns:
    print(df.select_dtypes(include='number').corr()['noise_col'])
else:
    print("noise_col is not numeric")

Age                 -0.005133
Glucose             -0.005358
Blood Pressure       0.002454
BMI                  0.000827
Oxygen Saturation   -0.005611
LengthOfStay         0.001976
Cholesterol         -0.004616
Triglycerides        0.008894
HbA1c                0.002478
Smoking              0.004599
Alcohol             -0.005346
Physical Activity    0.003471
Diet Score           0.002618
Family History       0.000763
Stress Level        -0.007119
Sleep Hours         -0.008360
noise_col            1.000000
Name: noise_col, dtype: float64

The column noise_col was removed because it contains random numeric values unrelated to patient health. Correlation analysis shows negligible relationship with all other numeric columns (correlation values near 0), confirming that it does not provide any meaningful information. Keeping this column would only introduce noise into the analysis, so it was dropped.

In [28]:
df.drop(columns=['random_notes','noise_col'],inplace=True)

In [29]:
df.columns

Index(['Age', 'Gender', 'Medical Condition', 'Glucose', 'Blood Pressure',
       'BMI', 'Oxygen Saturation', 'LengthOfStay', 'Cholesterol',
       'Triglycerides', 'HbA1c', 'Smoking', 'Alcohol', 'Physical Activity',
       'Diet Score', 'Family History', 'Stress Level', 'Sleep Hours'],
      dtype='object')

<h2>Data Validation or Detecting correct values are present in cols</h2>

In [30]:
df['Gender'].unique()

array(['Male', 'not_specified', 'Female'], dtype=object)

In [31]:
df['Medical Condition'].unique()

array(['Diabetes', 'Healthy', 'Asthma', 'Obesity', 'Hypertension',
       'Cancer', 'Unknown', 'Arthritis'], dtype=object)

In [32]:
cate_cols=df.select_dtypes(include='O').columns
numeric_cols=df.select_dtypes(exclude='O').columns

In [33]:
cate_cols

Index(['Gender', 'Medical Condition'], dtype='object')

In [34]:
numeric_cols

Index(['Age', 'Glucose', 'Blood Pressure', 'BMI', 'Oxygen Saturation',
       'LengthOfStay', 'Cholesterol', 'Triglycerides', 'HbA1c', 'Smoking',
       'Alcohol', 'Physical Activity', 'Diet Score', 'Family History',
       'Stress Level', 'Sleep Hours'],
      dtype='object')

In [35]:
for col in numeric_cols:
    if(df[col]<0).all():
        print(f"{col} -> negative value")
    else:
        print(f"{col} -> no")

Age -> no
Glucose -> no
Blood Pressure -> no
BMI -> no
Oxygen Saturation -> no
LengthOfStay -> no
Cholesterol -> no
Triglycerides -> no
HbA1c -> no
Smoking -> no
Alcohol -> no
Physical Activity -> no
Diet Score -> no
Family History -> no
Stress Level -> no
Sleep Hours -> no

<h2>Adding some New columns for our Analysis</h2>

<pre><h5>Age</h5>
age group       age range
child            0-17
young adult      18-35
middle age       36-55
senior            56+
</pre>

In [36]:
bins=[0,17,35,55,100]
labels=['child','young adult','middle age','senior']
df['Age_group']=pd.cut(df['Age'],bins=bins,labels=labels)

In [37]:
df.head()

,Age,Gender,Medical Condition,Glucose,Blood Pressure,BMI,Oxygen Saturation,LengthOfStay,Cholesterol,Triglycerides,HbA1c,Smoking,Alcohol,Physical Activity,Diet Score,Family History,Stress Level,Sleep Hours,Age_group
0,46.0,Male,Diabetes,137.04,135.27,28.90,96.04,6,231.88,210.56,7.61,0,0,-0.20,3.54,0,5.07,6.05,middle age
1,22.0,Male,Healthy,71.58,113.27,26.29,97.54,2,165.57,129.41,4.91,0,0,8.12,5.90,0,5.87,7.72,young adult
2,50.0,not_specified,Asthma,95.24,138.32,22.53,90.31,2,214.94,165.35,5.60,0,0,5.01,4.65,1,3.09,4.82,middle age
3,57.0,not_specified,Obesity,110.50,130.53,38.47,96.60,5,197.71,182.13,6.92,0,0,3.16,3.37,0,3.01,5.33,senior
4,66.0,Female,Hypertension,95.15,178.17,31.12,94.90,4,259.53,115.85,5.98,0,1,3.56,3.40,0,6.38,6.64,senior

<pre><h5>bmi</h5> 
category      bmi range
underweight   <18.5
normal         18.5-24.9
overweight     25-29.9
obese          >=30
</pre>

In [38]:
bins=[0,18.5,24.9,29.9,100]
label=["underweight","normal","overweight","obese"]
df['BMI_Category']=pd.cut(df['BMI'],bins=bins,labels=label)

<pre><h5>glucose</h5>
Risk Level     Glucose 
Normal          70–99
Prediabetic     100–125
Diabetic         ≥126
</pre>

In [39]:
def glucose_risk(x):
    if x > 500:
        return 'Extreme Outlier'
    elif x >= 126:
        return 'Diabetic'
    elif x >= 100:
        return 'Prediabetic'
    else:
        return 'Normal'

df['Glucose_Risk'] = df['Glucose'].apply(glucose_risk)

<pre><h5>Blood Pressure Category</h5>
Category        BP 
Normal          <120
Elevated        120–129
Hypertension     ≥130
</pre>

In [40]:
bins = [0, 120, 129, 300]
labels = ['Normal', 'Elevated', 'Hypertension']
df['BP_Category'] = pd.cut(df['Blood Pressure'], bins=bins, labels=labels)

<pre><h5>HbA1c Risk </h5>
Category       HbA1c 
Normal          <5.7
Prediabetic     5.7–6.4
Diabetic         ≥6.5
<pre

In [41]:
bins = [0, 5.7, 6.4, 20]
labels = ['Normal', 'Prediabetic', 'Diabetic']
df['HbA1c_Risk'] = pd.cut(df['HbA1c'], bins=bins, labels=labels)

<pre>
    <h5>Length of Stay Group</h5>
Label      Days
Short       0–3
Medium      4–7
Long        8–14
Very Long   15+

</pre>

In [42]:
bins = [0, 3, 7, 15, 100]
labels = ['Short', 'Medium', 'Long', 'Very Long']
df['LOS_Group'] = pd.cut(df['LengthOfStay'], bins=bins, labels=labels)

<pre>
Category       Lifestyle Index Range
Poor             ≤5
Average          6–12
Good              >12
</pre>

In [43]:
df['Lifestyle_Index'] = df['Physical Activity'] + df['Diet Score'] + df['Sleep Hours'] - df['Stress Level']

In [44]:
df['Lifestyle_Index'].min(),df['Lifestyle_Index'].max()

(np.float64(-5.27), np.float64(28.19))

In [45]:
bins = [-10, 5, 10, 30]  
labels = ['Poor', 'Average', 'Good']
df['Lifestyle_Category'] = pd.cut(df['Lifestyle_Index'], bins=bins, labels=labels)

In [46]:
df.head()

,Age,Gender,Medical Condition,Glucose,Blood Pressure,BMI,Oxygen Saturation,LengthOfStay,Cholesterol,Triglycerides,...,Stress Level,Sleep Hours,Age_group,BMI_Category,Glucose_Risk,BP_Category,HbA1c_Risk,LOS_Group,Lifestyle_Index,Lifestyle_Category
0,46.0,Male,Diabetes,137.04,135.27,28.90,96.04,6,231.88,210.56,...,5.07,6.05,middle age,overweight,Diabetic,Hypertension,Diabetic,Medium,4.32,Poor
1,22.0,Male,Healthy,71.58,113.27,26.29,97.54,2,165.57,129.41,...,5.87,7.72,young adult,overweight,Normal,Normal,Normal,Short,15.87,Good
2,50.0,not_specified,Asthma,95.24,138.32,22.53,90.31,2,214.94,165.35,...,3.09,4.82,middle age,normal,Normal,Hypertension,Normal,Short,11.39,Good
3,57.0,not_specified,Obesity,110.50,130.53,38.47,96.60,5,197.71,182.13,...,3.01,5.33,senior,obese,Prediabetic,Hypertension,Diabetic,Medium,8.85,Average
4,66.0,Female,Hypertension,95.15,178.17,31.12,94.90,4,259.53,115.85,...,6.38,6.64,senior,obese,Normal,Hypertension,Prediabetic,Medium,7.22,Average

The Lifestyle_Index is a single score that shows how healthy a person’s lifestyle is. It adds together their physical activity, diet, and sleep, and subtracts stress. A higher score means a healthier lifestyle, while a lower score shows more unhealthy habits. This makes it easy to compare people and see who may need to improve their lifestyle.

In [47]:
df.shape

(30000, 26)

In [48]:
df.to_csv("cleaned_hrf.csv",index=False)